# Generated by Django 4.1.5 on 2023-01-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='rating_author',
            field=models.IntegerField(default=0),
        ),
    ]
