# Generated by Django 4.1.5 on 2023-01-28 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory',
            name='amount',
        ),
    ]
