# Generated by Django 4.1.5 on 2023-01-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_post_postcategory_post_categorys_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating_comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='rating_post',
            field=models.IntegerField(default=0),
        ),
    ]
