# Generated by Django 4.1.5 on 2023-02-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_remove_new_price_remove_new_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='description1',
            field=models.TextField(default='kek'),
        ),
    ]
