# Generated by Django 4.1.5 on 2023-02-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_remove_new_description1_new_data_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='data_public',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
