# Generated by Django 4.1.5 on 2023-02-15 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_new_change_new_rating_post_remove_new_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='author',
            field=models.ForeignKey(default='Никто', on_delete=django.db.models.deletion.CASCADE, to='newsapp.author'),
        ),
    ]
