# Generated by Django 4.2.3 on 2023-08-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0008_alter_new_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('image', models.URLField(blank=True)),
            ],
        ),
    ]
