# Generated by Django 4.2.3 on 2023-08-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0009_newsout'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsout',
            name='data_public_from_site',
            field=models.CharField(default='default_value_here', max_length=100),
        ),
        migrations.AddField(
            model_name='newsout',
            name='site',
            field=models.CharField(default='default_value_here', max_length=100),
        ),
    ]
