# Generated by Django 4.2.3 on 2023-08-12 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0011_rename_data_public_new_data_public_from_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='data_public_from_site',
            new_name='data_public',
        ),
    ]
